DROP TABLE IF EXISTS pdf_content;

CREATE TABLE pdf_content (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  metadata INTEGER NOT NULL,
  pdf_name TEXT UNIQUE   NOT NULL,
  uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  author TEXT NOT NULL,
  body TEXT NOT NULL,
  title TEXT NOT NULL
);